#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : goaccess
Version  : 1.4
Release  : 7
URL      : https://tar.goaccess.io/goaccess-1.4.tar.gz
Source0  : https://tar.goaccess.io/goaccess-1.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: goaccess-bin = %{version}-%{release}
Requires: goaccess-license = %{version}-%{release}
Requires: goaccess-locales = %{version}-%{release}
Requires: goaccess-man = %{version}-%{release}
BuildRequires : intltool-dev
BuildRequires : ncurses-dev
BuildRequires : openssl-dev

%description
What is it?
-------------
GoAccess is an open source real-time web log analyzer and interactive viewer
that runs in a terminal in *nix systems or through your browser.

%package bin
Summary: bin components for the goaccess package.
Group: Binaries
Requires: goaccess-license = %{version}-%{release}

%description bin
bin components for the goaccess package.


%package license
Summary: license components for the goaccess package.
Group: Default

%description license
license components for the goaccess package.


%package locales
Summary: locales components for the goaccess package.
Group: Default

%description locales
locales components for the goaccess package.


%package man
Summary: man components for the goaccess package.
Group: Default

%description man
man components for the goaccess package.


%prep
%setup -q -n goaccess-1.4
cd %{_builddir}/goaccess-1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1601673234
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --enable-utf8 \
--with-openssl \
--disable-bzip
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1601673234
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/goaccess
cp %{_builddir}/goaccess-1.4/COPYING %{buildroot}/usr/share/package-licenses/goaccess/8a576e16fe244dc2a95607970b255d83d97173e1
%make_install
%find_lang goaccess

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/goaccess

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/goaccess/8a576e16fe244dc2a95607970b255d83d97173e1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/goaccess.1

%files locales -f goaccess.lang
%defattr(-,root,root,-)

